### ISSUE TITLE
Problem in installing Nuclear Boy

### ISSUE THREAD

**Issue by Sabyaro** [ahnaf-tahmid-chowdhury/NuclearBoy#1]
I have tried to install Nuclear Boy on my PC and it shows error message:

Error compiling Cython file:
                                       ------------------------------------------------------------
                       ...
                                      cdef moab.ErrorCode err
                                                                         cdef Range entities = Range()
                                  cdef moab.EntityType typ = entity_type
                                                                                    cdef vector[eh.EntityHandle] hvec
                                                 if as_list:
                                                                            err = self.inst.get_entities_by_type(<unsigned long> meshset,
                                                                                                             ^
                                  ------------------------------------------------------------
                  
                      pymoab/core.pyx:1548:48: no suitable method found
                                                                           
                                                                               Error compiling Cython file:
                               ------------------------------------------------------------
               ...
                              """
                                             cdef moab.ErrorCode err
                                                                                cdef Range ents = Range()
                                     cdef vector[eh.EntityHandle] hvec
                                                                                  if as_list:
                             err = self.inst.get_entities_by_handle(<unsigned long> meshset, hvec, recur)
                                                                               ^
                                                                                   ------------------------------------------------------------
                                                                   
                                                                       pymoab/core.pyx:1711:50: no suitable method found
                                            
                                                Error compiling Cython file:
                                                                                ------------------------------------------------------------
                                                                ...
                                                                               """
              cdef moab.ErrorCode err
                                                 cdef Range ents = Range()
                                                                                      cdef vector[eh.EntityHandle] hvec
                                                   if as_list:
                                                                              err = self.inst.get_entities_by_dimension(<unsigned long> meshset, dimension, hvec, recur)
                                                                 ^
                                                                      ------------------------------------------------------------
                                                      
                                                          pymoab/core.pyx:1751:53: no suitable method found
                               Traceback (most recent call last):
                                                                       File "<string>", line 2, in <module>
                                 File "<pip-setuptools-caller>", line 34, in <module>
           File "/home/dresden/NuclearBoy/nuclear-boy/moab-repo/build/pymoab/setup.py", line 53, in <module>
                                    setup(
                                                File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
           return distutils.core.setup(**attrs)
                                                     File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
                                             dist.run_commands()
                                                                      File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
                                                                     self.run_command(cmd)
                File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
              cmd_obj.run()
                                 File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
                                                                                self.install_for_development()
                                    File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/setuptools/command/develop.py", line 114, in install_for_development
                        self.run_command('build_ext')
                                                           File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
                                                        self.distribution.run_command(command)
                    File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
                  cmd_obj.run()
                                     File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
                                        self.build_extensions()
                                                                     File "/usr/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
                                                                                     self._build_extensions_serial()
                                          File "/usr/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
                                                                  self.build_extension(ext)
                 File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
                                                                             new_ext = cythonize(
                       File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
                                                                             cythonize_one(*args)
                       File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
                                                                                 raise CompileError(None, pyx_file)
                                       Cython.Compiler.Errors.CompileError: pymoab/core.pyx
               Compiling pymoab/core.pyx because it changed.
                                                                [1/1] Cythonizing pymoab/core.pyx
                     [end of output]

                                    note: This error originates from a subprocess, and is likely not a problem with pip.
                                        make[2]: *** [pymoab/CMakeFiles/pymoab-local-install.dir/build.make:71: pymoab/CMakeFiles/pymoab-local-install] Error 1
                                                                               make[1]: *** [CMakeFiles/Makefile2:1266: pymoab/CMakeFiles/pymoab-local-install.dir/all] Error 2
               make: *** [Makefile:146: all] Error 2
               
               
               
               
               
For additional information I am using Ubuntu 22.04 and I am not using Anaconda. Thank you sir if you can help, that would be very helpful to me. Thank you

**Comment by ahnaf-tahmid-chowdhury** [comment]
Hi @Sabyaro, I apologize for the inconvenience during the installation process. It appears that `pymoab` is not compatible with the latest Cython v3. I'm considering creating a pull request to address this issue and fix it.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Hi @Sabyaro, you can try now. I have downgraded `Cython` to v0.29. Let me know if you encounter any other issues during the installation process.

**Comment by Sabyaro** [comment]
The previous problem has been solved. But again it shows some error message: 

 make[2]: *** [CMakeFiles/G4NDL.dir/build.make:98: Externals/G4NDL-4.7/src/G4NDL-stamp/G4NDL-download] Error 1
                                                                  make[1]: *** [CMakeFiles/Makefile2:943: CMakeFiles/G4NDL.dir/all] Error 2
                                                           make: *** [Makefile:156: all] Error 2


If you be able to solve this please help me in this regard.

**Comment by ahnaf-tahmid-chowdhury** [comment]
The `Error 1` and `Error 2` are generic indications that something went wrong during the build. To diagnose and solve the issue, we'll need more information about the context and the steps you've taken so far.

**Comment by Sabyaro** [comment]
It shows some errors like: 

                       [1 bytes data]

                                       [16320 bytes data]

                                                           TLSv1.2 (IN), TLS header, Supplemental data (23):

                              [5 bytes data]

                                              [1 bytes data]

                                                              [16384 bytes data]

                                                                                 TLSv1.2 (IN), TLS header, Supplemental data (23):

                                                    [5 bytes data]

                                                                    [1 bytes data]

    [16320 bytes data]

                        TLSv1.2 (IN), TLS header, Supplemental data (23):

                                                                           [5 bytes data]

           [1 bytes data]

                           [16384 bytes data]

                                               TLSv1.2 (IN), TLS header, Supplemental data (23):

                  [5 bytes data]

                                  [1 bytes data]

                                                  [16320 bytes data]

                                                                      TLSv1.2 (IN), TLS header, Supplemental data (23):

                                         [5 bytes data]

                                                         [1 bytes data]

                                                                         [16384 bytes data]

             TLSv1.2 (IN), TLS header, Supplemental data (23):

                                                                [5 bytes data]

                                                                                [1 bytes data]

                [16320 bytes data]

                                    TLSv1.2 (IN), TLS header, Supplemental data (23):

       [5 bytes data]

                       [1 bytes data]

                                       [16384 bytes data]

                                                           TLSv1.2 (IN), TLS header, Supplemental data (23):

                              [5 bytes data]

                                              [1 bytes data]

                                                              [16320 bytes data]

                                                                                 TLSv1.2 (IN), TLS header, Supplemental data (23):

                                                    [5 bytes data]

                                                                    [1 bytes data]

    [16384 bytes data]

                        TLSv1.2 (IN), TLS header, Supplemental data (23):

                                                                           [5 bytes data]

           [1 bytes data]

                           [16320 bytes data]

I have followed the in installation script as you have mentioned in the script. I think the problem is creating while installation of geant4.

**Comment by ahnaf-tahmid-chowdhury** [comment]
It looks like the data you've provided is a sequence of TLS (Transport Layer Security) records. These are not errors. Can you provide me last 100 lines of the log. However, the log is difficult to read, not sure, but assuming you are using a custom terminal or font?

**Comment by Sabyaro** [comment]
sorry but it shows sequentially in this way. How can I get myself out from this problem? 
[Screencast from 26-8-23 11:02:03 পূর্বাহ্ণ +06.webm](https://github.com/ahnaf-tahmid-chowdhury/NuclearBoy/assets/94109272/31c8bf2e-e48d-4caa-bd12-e76d59a5f8af)
I have no idea about TLS. I have tried several times running the code as you have given in the script but failed.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Can you provide me the error logs above the TLS log?

**Comment by ahnaf-tahmid-chowdhury** [comment]
I think you have a network issue. Try Install Geant4 data? (y/n): n.

you may need to download Geant4 data manually after installation from their website and extract them to your desired folder later.

**Comment by Sabyaro** [comment]
Yes sir Geant4 has installed correctly. but now it shows some problems like: 
                                                                              ERROR: Exception:
                                                                                               Traceback (most recent call last):
                                                                                                                                   File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
                                                                                                                      yield
                                                                                                                             File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
                                                                                                      data = self._fp.read(amt) if not fp_closed else b""
     File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
                                                                                                                                           data = self.__fp.read(amt)
                 File "/usr/lib/python3.10/http/client.py", line 466, in read
                                                                                 s = self.fp.read(amt)
                                                                                                        File "/usr/lib/python3.10/socket.py", line 705, in readinto
                 return self._sock.recv_into(b)
                                                 File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
                                                                                                               return self.read(nbytes, buffer)
                                                                                                                                                 File "/usr/lib/python3.10/ssl.py", line 1130, in read
                                                    return self._sslobj.read(len, buffer)
                                                                                         TimeoutError: The read operation timed out

                                                                                                                                   During handling of the above exception, another exception occurred:

                                                Traceback (most recent call last):
                                                                                    File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
                                                                              status = run_func(*args)
                                                                                                        File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
                                                                                     return func(self, options, args)
                                                                                                                       File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 339, in run
                                                                                                 requirement_set = resolver.resolve(
                                                                                                                                      File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
                                                                                                                                 result = self._result = resolver.resolve(
                      File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
      state = resolution.resolve(requirements, max_rounds=max_rounds)
                                                                       File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
                                                       failure_causes = self._attempt_to_pin_criterion(name)
                                                                                                              File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
                                                                                                                criteria = self._get_updated_criteria(candidate)
            File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
          self._add_to_criteria(criteria, requirement, parent=candidate)
                                                                          File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
                                                                   if not criterion.candidates:
                                                                                                 File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
                                                                                return bool(self._sequence)
                                                                                                             File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
                                                                                                                  return any(self)
                                                                                                                                    File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
                                                                                                                                          return (c for c in iterator if id(c) not in self._incompatible_ids)
                                                         File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
                                                                candidate = func()
                                                                                    File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
                                                                                                 self._link_candidate_cache[link] = LinkCandidate(
                                                                                                                                                    File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
                                                                                                                                                   super().__init__(
                File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
               self.dist = self._prepare()
                                            File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
                                           dist = self._prepare_distribution()
                                                                                File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
                                                                                            return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
                    File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
                       return self._prepare_linked_requirement(req, parallel_builds)
                                                                                      File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 532, in _prepare_linked_requirement
                                                                                          local_file = unpack_url(
                                                                                                                    File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 214, in unpack_url
                                                                                                       file = get_http_url(
                                                                                                                             File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 94, in get_http_url
                                                                                                                 from_path, content_type = download(link, temp_dir.path)
                    File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/network/download.py", line 146, in __call__
                                                                                                                                                         for chunk in chunks:
                         File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 304, in _rich_progress_bar
                   for chunk in iterable:
                                           File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
                             for chunk in response.raw.stream(
                                                                File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
                                           data = self.read(amt=amt, decode_content=decode_content)
                                                                                                     File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 512, in read
                                                                              with self._error_catcher():
                                                                                                           File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
                        self.gen.throw(typ, value, traceback)
                                                               File "/home/dresden/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
                                                  raise ReadTimeoutError(self._pool, None, "Read timed out.")
                                                                                                             pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.


Is this happened due to network issue?

**Comment by ahnaf-tahmid-chowdhury** [comment]
Yes. Your network connection was lost.

**Comment by Sabyaro** [comment]
Ok thank you sir. I am trying it for another time

**Comment by ahnaf-tahmid-chowdhury** [comment]
To expedite, you can annotate the script with comments highlighting the packages already installed.

```sh
main() {
  detect_os
  detect_version_id
  echo "Welcome to the Nuclear Boy installer!"
  echo "This script will install the PyNE, OpenMC, DAGMC and Geant4 on your system."
  echo
  set_install_directory
  set_env_name
  #set_geant4_data_lib
  #auto_install_geant4_data
  get_sudo_password
  #setup_dependencies
  #setup_python_env
  source $env_dir/bin/activate
  set_ld_library_path
  #install_moab
  #install_geant4
  install_dagmc
  install_openmc
  install_pyne
  create_program_file
  create_shortcut
  echo "==============================================="
  echo "Nuclear Boy installation finished"
  echo "To activate Nuclear Boy in your terminal type:"
  echo "source ${env_name}"
  echo "Recommended packages can be installed through:"
  echo "pip3 install -r packages.txt --default-timeout=0"
  echo "================================================"
}
main
```

**Comment by Sabyaro** [comment]
ok sir. that's helpful for me. Thanks a lot sir

**Comment by Sabyaro** [comment]
Thank you, sir. I have successfully installed it.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Glad to hear that. I am working on building a method to download and extract all ENDF data after installing OpenMC. Then, I will create a method that allows us to choose which ENDF library we would like to use from the terminal. You can check the develop branch.
